"""SQL DDL generation.

Emits ``CREATE TABLE`` for every table in the model, in an order that lets the
whole file run against an empty database: dimensions first, then bridges, then
facts, because a foreign key cannot be declared before its target exists.

Nothing here is timestamped and nothing depends on the environment. That is
not a stylistic preference — a generated file that changes when nothing about
the model changed makes "is this output current?" unanswerable, and turns
every regeneration into a diff nobody reads.
"""

from __future__ import annotations

import textwrap
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .ext import Context
    from .model import Column, DimensionalModel, Table

#: LinkML range to SQL type. Deliberately a closed table with no fallback:
#: an unmapped range raises rather than quietly becoming TEXT, because a
#: column silently typed as text is a bug that surfaces years later as a
#: comparison that does not do what it looks like.
TYPES = {
    "string": "VARCHAR",
    "integer": "INTEGER",
    "float": "DOUBLE PRECISION",
    "double": "DOUBLE PRECISION",
    "decimal": "NUMERIC",
    "boolean": "BOOLEAN",
    "date": "DATE",
    "datetime": "TIMESTAMP",
    "time": "TIME",
    "uri": "VARCHAR",
    "uriorcurie": "VARCHAR",
    "ncname": "VARCHAR",
}


class GenerationError(Exception):
    """A model cannot be generated from, and the run must stop."""


def sql_type(column: Column) -> str:
    """Map a column's range to a SQL type, or raise naming the column."""
    rng = column.range
    mapped = TYPES.get(rng.lower())
    if mapped is None:
        known = ", ".join(sorted(TYPES))
        msg = (
            f"{column}: range {rng!r} has no SQL mapping. Known ranges: {known}"
        )
        raise GenerationError(msg)
    return mapped


def _comment(text: str, label: str = "") -> list[str]:
    """Wrap a comment at the line limit.

    The output is read by people even though it is written by a machine, and
    a comment that runs to 300 columns is one nobody reads in a terminal.
    """
    body = f"{label}{text}" if label else text
    return [f"-- {line}" for line in textwrap.wrap(body, width=77)]


def _ordered(model: DimensionalModel) -> list[Table]:
    """Order tables so every foreign key's target is already created."""
    return [*model.dimensions, *model.bridges, *model.facts]


def _column_line(column: Column) -> str:
    parts = [f"    {column.physical}", sql_type(column)]
    if column.role == "surrogate_key":
        parts.append("PRIMARY KEY")
    elif column.required:
        parts.append("NOT NULL")
    return " ".join(parts)


def _table(table: Table, schema: str) -> str:
    """Render one CREATE TABLE, with its grain as a comment."""
    lines: list[str] = []
    if table.description:
        lines += _comment(table.description)
    if table.grain:
        lines += _comment(table.grain, "Grain: ")
    if table.scd:
        lines += _comment(table.scd, "Slowly-changing: ")
    lines.append(f"CREATE TABLE {schema}.{table.physical} (")

    body = [_column_line(c) for c in table.columns]
    for fk in table.foreign_keys:
        target = fk.table.model.table(fk.references or "")
        if target is None:
            continue  # V109 already reported it; do not also crash here
        key = target.surrogate_keys
        if not key:
            continue  # V105's business
        body.append(
            f"    FOREIGN KEY ({fk.physical}) REFERENCES "
            f"{schema}.{target.physical} ({key[0].physical})"
        )
    lines.append(",\n".join(body))
    lines.append(");")
    return "\n".join(lines)


def generate(model: DimensionalModel, schema: str = "mart") -> str:
    """Render the whole model as one runnable DDL script."""
    header = [
        "-- Generated by varda. Do not edit.",
        f"-- Source: {model.source.name}",
        "",
        f"CREATE SCHEMA IF NOT EXISTS {schema};",
        "",
        "",
    ]
    blocks = [_table(t, schema) for t in _ordered(model)]
    return "\n".join(header) + "\n\n".join(blocks) + "\n"


def run(ctx: Context) -> dict[str, str]:
    """Run this generator and return its artefacts."""
    return {"sql/mart.sql": generate(ctx.model, ctx.schema)}
