"""Documentation generation.

Emits one Markdown reference for the whole model. The audience is an analyst
deciding whether a table answers their question, so the ordering is facts
first — a fact is what someone starts from — and the grain sentence is given
the most prominent position it can have.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .ext import Context
    from .model import DimensionalModel, Table

ADDITIVITY = {
    "additive": "sums across every dimension",
    "semi_additive": "does not sum across",
    "non_additive": "never sum; recompute from components",
}


def _columns(table: Table) -> list[str]:
    rows = [
        "| Column | Role | Type | Notes |",
        "| --- | --- | --- | --- |",
    ]
    for column in table.columns:
        notes: list[str] = []
        if column.references:
            notes.append(f"→ `{column.references}`")
        if column.additivity:
            phrase = ADDITIVITY.get(column.additivity, column.additivity)
            if column.additivity == "semi_additive" and (
                column.semi_additive_over
            ):
                phrase = f"{phrase} `{column.semi_additive_over}`"
            notes.append(phrase)
        if column.unit:
            notes.append(f"unit: `{column.unit}`")
        if column.description:
            notes.append(column.description)
        rows.append(
            f"| `{column.physical}` | {column.role or '—'} | "
            f"{column.range} | {'; '.join(notes) or '—'} |"
        )
    return rows


def _table(table: Table) -> str:
    lines = [f"### {table.name}", ""]
    if table.description:
        lines += [table.description, ""]
    facts = [f"**Physical name:** `{table.physical}`"]
    if table.grain:
        facts.append(f"**Grain:** {table.grain}")
    if table.fact_type:
        facts.append(f"**Fact type:** {table.fact_type}")
    if table.scd:
        facts.append(f"**Slowly-changing:** {table.scd}")
    lines += [*facts, "", *_columns(table), ""]
    return "\n".join(lines)


def generate(model: DimensionalModel) -> str:
    """Render the model as a Markdown reference."""
    out = [
        "# Model reference",
        "",
        "Generated by varda. Do not edit.",
        "",
        f"Source: `{model.source.name}`",
        "",
    ]
    for heading, tables in (
        ("Facts", model.facts),
        ("Dimensions", model.dimensions),
        ("Bridges", model.bridges),
    ):
        if not tables:
            continue
        out += [f"## {heading}", ""]
        out += [_table(t) for t in tables]
    return "\n".join(out).rstrip() + "\n"


def run(ctx: Context) -> dict[str, str]:
    """Run this generator and return its artefacts."""
    return {"docs/model.md": generate(ctx.model)}
